keys:
 - &user_bddvlpr age16aazmlnarycwuk3a9e5sr55e2354sydn9qd5c6edhly9rq9k693s43txeq

creation_rules:
  - path_regex: systems/rena/[^/]+\.yaml$
    key_groups:
      - age:
          - *user_bddvlpr
